CREATE STREAM JOIN_EVENTS AS
SELECT
	SL.ID ID,
    SL.DEVICE_ID DEVICE_ID,
    SL.LATITUDE,
    SL.LONGITUDE,
    GEO_DISTANCE(SL.LATITUDE, SL.LONGITUDE, 9.0, 107.0) DISTANCE,
    SL.EVENT_TS EVENT_TS,

    SS.DEVICE_ID as DI_,
    SS.temperature,
    SS.sound,
    SS.altitude
FROM STREAM_LOCATION AS SL
LEFT JOIN STREAM_STATUS AS SS
    WITHIN 2 SECONDS
	ON SL.DEVICE_ID = SS.DEVICE_ID
WHERE
    1=1
    and SL.LATITUDE BETWEEN 8 AND 10
    and SL.LONGITUDE BETWEEN 106 AND 108
EMIT CHANGES;
