CREATE TABLE device_winagg_status_per2s
WITH (
	KEY_FORMAT   = 'AVRO',
	VALUE_FORMAT = 'AVRO'
) AS
SELECT
	CONCAT( CAST(DEVICE_ID AS STRING), '_', CAST(WINDOWSTART AS STRING), '_', CAST(WINDOWEND AS STRING)) AS ID,
	DEVICE_ID,
	AS_VALUE(DEVICE_ID) as "dev_id",
	AVG(LATITUDE) LATITUDE,
	AVG(LONGITUDE) LONGITUDE,
	AVG(DISTANCE) DISTANCE,

	MAX(EVENT_TS) EVENT_TS,
	COUNT(*) AS event_count,
	AVG(TEMPERATURE) as avg_temp,
	AVG(SOUND) as avg_sound,
	AVG(ALTITUDE) as avg_alt
FROM JOIN_EVENTS
WINDOW TUMBLING (SIZE 2 SECONDS)
GROUP BY DEVICE_ID
EMIT CHANGES;
