CREATE TABLE device_winagg_status_perdevice
WITH (
	KEY_FORMAT   = 'AVRO',
	VALUE_FORMAT = 'AVRO'
) AS
SELECT
    DEVICE_ID,
    LATEST_BY_OFFSET(LATITUDE) AS LATITUDE,
    LATEST_BY_OFFSET(LONGITUDE) AS LONGITUDE,
    LATEST_BY_OFFSET(DISTANCE) AS DISTANCE,
    LATEST_BY_OFFSET(EVENT_TS) AS EVENT_TS,
    LATEST_BY_OFFSET(TEMPERATURE) AS TEMPERATURE,
    LATEST_BY_OFFSET(SOUND) AS SOUND,
    LATEST_BY_OFFSET(ALTITUDE) AS ALTITUDE
FROM JOIN_EVENTS
GROUP BY DEVICE_ID
EMIT CHANGES;
